Repository maketheworldwise/play-keyboard-react-bitbyte, pull requests merged in 2022-10, with the labels that each got.

#7 Feature: 테마 상세 정보 컴포넌트 구현
  public/mocks/Detail/getDetail.json
  src/Assets/Svgs/ic_all_share.svg
  src/Components/DetailInfo/DetailInfo.js
  src/Components/DetailInfo/DetailInfo.module.scss
  src/Components/DetailInfo/HashTag/HashTag.js
  src/Components/DetailInfo/HashTag/HashTag.module.scss
  src/Components/DetailInfo/HashTag/HashTagContainer.js
  src/Components/DetailInfo/HashTag/HashTagContainer.module.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.module.scss
Labels: ✨ Feature, 💄 UI

#9 Feature: 테마 상세 뒤로가기 버튼
  src/Assets/Svgs/ic_all_back.svg
  src/Components/DetailInfo/DetailInfo.js
  src/Components/DetailInfo/DetailInfo.module.scss
Labels: ✨ Feature

#12 Feature/category
  src/Pages/Main/Category.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.module.scss
Labels: ✨ Feature, 💄 UI, 🎨 Modify

#14 UI : 상단 header
  package-lock.json
  package.json
  src/Components/Header/Header.js
  src/assets/Svgs/search.png
  src/assets/Svgs/top_nav/battery.png
  src/assets/Svgs/top_nav/signal.png
  src/assets/Svgs/top_nav/wifi.png
  src/assets/logo.png
Labels: 💄 UI

#13 UI : 하단 navbar(footer)구현
  src/Assets/Svgs/bottom_nav/admin.png
  src/Assets/Svgs/bottom_nav/admin_p.png
  src/Assets/Svgs/bottom_nav/bell.png
  src/Assets/Svgs/bottom_nav/bell_p.png
  src/Assets/Svgs/bottom_nav/dia.png
  src/Assets/Svgs/bottom_nav/dia_p.png
  src/Assets/Svgs/bottom_nav/heart.png
  src/Assets/Svgs/bottom_nav/heart_p.png
  src/Assets/Svgs/bottom_nav/store.png
  src/Assets/Svgs/bottom_nav/store_p.png
  src/Components/Footer/Footer.js
Labels: 💄 UI, 🧑‍🎨 Style

#15 Feature/theme emoticon
  src/Components/page2/Emoticons.js
  src/Pages/Detail/Detail.js
Labels: 🏗 Structure, 🧑‍🎨 Style

#10 UI: 하단 이모티콘&버튼 구현
  src/Assets/Svgs/cheer.svg
  src/Assets/Svgs/have.svg
  src/Assets/Svgs/heart.svg
  src/Assets/Svgs/icon_dia.svg
  src/Assets/Svgs/like.svg
  src/Components/DetailFooter/DetailButton.js
  src/Components/DetailFooter/DetailEmoji.js
  src/Components/Header/Header.js
  src/Pages/Detail/Detail.js
  src/Router.js
Labels: ✨ Feature, 💄 UI

#16 Feature/category
  src/Pages/Main/Category.js
  src/Pages/Main/Main.js
Labels: 🎨 Modify

#17 UI: 테마 카드리스트 레이아웃 구현
  package-lock.json
  package.json
  public/mocks/Detail/getDetail.json
  src/Assets/Images/Theme-preview.png
  src/Assets/Svgs/ic_all_download.svg
  src/Assets/Svgs/ic_all_zem.svg
  src/Components/ThemeCard/ThemeCard.jsx
  src/Components/ThemeCard/ThemeCardList.jsx
  src/Pages/Main/Main.js
Labels: ✨ Feature, 💄 UI

#19 Feature/theme emoticon
  src/Components/page2/Emoticons.js
Labels: 🧑‍🎨 Style, 🎨 Modify

#20 Fix - 하단&이모티콘 css 수정
  src/Components/DetailFooter/DetailButton.js
  src/Components/DetailFooter/DetailEmoji.js
Labels: 🧑‍🎨 Style, 🎨 Modify

#22 Fix : 사이즈 em으로 변경
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Pages/Main/Main.js
  src/Router.js
Labels: 🎨 Modify

#23 Modify: 코드 수정
  src/Components/Footer/Footer.js
  src/Components/ThemeCard/ThemeCard.jsx
  src/Components/ThemeCard/ThemeCardList.jsx
  src/Pages/Main/Category.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.module.scss
Labels: 🔥 Remove, 🎨 Modify

#26 [Modify] style수정
  package-lock.json
  src/Components/Category/Category.js
  src/Pages/Main/Main.js
Labels: 🎨 Modify

#27 Style: css 중복 코드 재사용
  src/Components/ThemeCard/ThemeCard.js
  src/Components/ThemeCard/ThemeCardList.js
Labels: 🧑‍🎨 Style

#28 Feature/theme emoticon 코드 리팩토링 및 수정사항 반영
  src/Components/page2/Emoticons.js
  src/Pages/Detail/Detail.js
Labels: 🔨 Refactor, 🧑‍🎨 Style, 🎨 Modify

#24 Feature: 이모지 클릭할 때 스타일, count 추가
  src/Components/DetailFooter/DetailButton.js
  src/Components/DetailFooter/DetailEmoji.js
  src/Components/Examples/EmoticonFeatures/EmoticonFeatures.js
  src/Components/Examples/EmoticonFeatures/EmoticonFeatures.module.scss
  src/Components/Examples/EmoticonList/Emoticon.js
  src/Components/Examples/EmoticonList/Emoticon.module.scss
  src/Components/Examples/EmoticonList/EmoticonList.js
  src/Components/Examples/EmoticonList/EmoticonList.module.scss
  src/Components/Examples/EmoticonReviews/EmoticonReview.js
  src/Components/Examples/EmoticonReviews/EmoticonReview.module.scss
  src/Components/Examples/EmoticonReviews/EmoticonReviews.js
  src/Components/Examples/EmoticonReviews/EmoticonReviews.module.scss
  src/Pages/Detail/Detail.js
Labels: ✨ Feature

#30 Feature/category
  src/Components/Category/Category.js
Labels: 🎨 Modify

#31 Feature: 한글 키보드 모달창 구현
  package-lock.json
  package.json
  src/Components/EmoticonInfo/EmoticonInfo.js
  src/Components/EmoticonInfo/Keyboard/keyboardConfig.js
Labels: ✨ Feature, 💄 UI

#34 Fix: 한글 키보드 모달창 팝업 높이 조절
  package-lock.json
  src/Components/EmoticonInfo/EmoticonInfo.js
Labels: 🐛 Bug, 🎨 Modify
